.TH "sensordata" 3 "Mon Jun 28 2021" "IPASS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sensordata
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int16_t \fBx\fP = 0"
.br
.ti -1c
.RI "int16_t \fBy\fP = 0"
.br
.ti -1c
.RI "int16_t \fBz\fP = 0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for IPASS from the source code\&.
